version: 2
machine:
  pre:
    - curl -s https://packagecloud.io/install/repositories/circleci/trusty/script.deb.sh | sudo bash
    - sudo apt-get install circleci-php-7.0.4=4
  php:
    version: 7.0.4
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore npm Package Data Cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Grunt CLI
          command: sudo npm install -g grunt-cli
      - run:
          name: Install Node dependencies
          command: npm install
      - save_cache:
          name: Cache npm Package Data
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint Source
          command: npm run test
