version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore npm Package Data Cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install gettext
          command: sudo apt-get install gettext
      - run:
          name: Install Grunt CLI
          command: sudo npm install -g grunt-cli
      - run:
          name: Install Node dependencies
          command: npm install
      - save_cache:
          name: Cache npm Package Data
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint Source
          command: npm run test
